name: entrenaapp
description: EntrenaAPP es una aplicación gratuita de entrenamiento personalizado a medida.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  responsive_builder: ^0.3.0
  html: ^0.14.0+4
  auto_size_text: ^2.1.0
  
  excel: ^2.0.0-null-safety
  
  http: ^0.13.0
  firebase_auth_oauth: ^1.0.1
 
  firebase_auth: ^1.0.1
  google_sign_in: ^4.1.0
  flutter_facebook_login_web: ^0.2.1+1
  flutter_bloc: 
 
  flutter_signin_button: ^2.0.0
  flutter_auth_buttons: ^0.10.0
  drawerbehavior: ^2.0.0+4
  mailto: ^1.0.0
  url_launcher: ^6.0.3
  shared_preferences: ^2.0.5
  firebase_storage: ^8.0.1
 
  firebase: ^9.0.1
  js: ^0.6.2
  webview_flutter: ^1.0.7
  dio: ^4.0.0
  getwidget: ^1.1.0
  flutter_typeahead: ^3.1.1

  firebase_messaging: ^9.1.0
  firebase_core: ^1.0.2
  file_picker: ^3.0.0
  data_tables: ^1.3.2
  device_preview: 
  

  equatable:
  flutter_form_builder: ^6.0.1
  fa_stepper: ^0.0.2
  
  simple_animations: ^3.1.1
  rflutter_alert: ^1.1.0
  percent_indicator: "^2.1.1"
  badges: ^1.1.1
 
  fab_circular_menu: ^1.0.0
  flip_card: ^0.4.4

  path_provider: ^2.0.2

 
  
  
  

  
  
  shimmer: ^1.1.1
  community_material_icon: ^3.5.95
  video_player: ^1.0.1
 

  stepper_touch: ^0.0.1
  animated_text_kit: ^2.0.0
  
  row_collection: ^0.2.4
  
   
  
 
 

  connectivity: ^3.0.6
  introduction_screen: ^1.0.9
  folding_cell: ^1.0.2
  
  

  fl_chart: ^0.36.1
 

  liquid_swipe: ^2.1.0


  

  
  timer_builder: ^1.3.0



  

 
  

  


  diacritic: ^0.1.1
  easy_localization: ^3.0.0

 
  
  


 
  meta:
  rxdart:



  

 
 
  
 
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
       
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
